"""SQLAlchemy models.

Table *shapes* are carried over from the prototype (see PORTING.md) so the
ported report/RAG logic keeps working. Three deliberate changes:

1. **UUID primary keys** replace the prototype's parsed sequential strings
   ("UR-1001" -> "UR-1002"). Those were generated by reading the max existing
   id, string-slicing it and adding one, which sorted lexicographically
   ("REP-999" > "REP-1000") and raced between concurrent requests.
2. **Lowercase table names.** The prototype used "USER", which is a reserved
   word in Postgres and only worked because SQLAlchemy quoted it.
3. **`server_default=func.now()`** instead of `default=datetime.now()`. The
   latter evaluates once at import, so every row in a given process shares the
   process start time.

Column names within each table are otherwise unchanged.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    Uuid,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


def _pk() -> Mapped[uuid.UUID]:
    return mapped_column(Uuid, primary_key=True, default=uuid.uuid4)


class Users(Base):
    __tablename__ = "users"

    user_id: Mapped[uuid.UUID] = _pk()
    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True, index=True)
    role: Mapped[str] = mapped_column(String(50), nullable=False, default="analyst")
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="Active")
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    phone_number: Mapped[str | None] = mapped_column(String(50))
    # bcrypt hash. Never a plaintext password — see CLAUDE.md > Hard rules.
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    organization: Mapped[str] = mapped_column(String(255), nullable=False, default="-")
    location: Mapped[str] = mapped_column(String(255), nullable=False, default="UAE")
    bio: Mapped[str | None] = mapped_column(Text)
    photo_path: Mapped[str | None] = mapped_column(String(500))
    mfa: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    documents: Mapped[list[Document]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    reports: Mapped[list[Report]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    chats: Mapped[list[Chat]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class Document(Base):
    __tablename__ = "documents"

    document_id: Mapped[uuid.UUID] = _pk()
    document_name: Mapped[str] = mapped_column(String(255), nullable=False)
    document_size: Mapped[float] = mapped_column(Float, nullable=False)
    document_extension: Mapped[str] = mapped_column(String(20), nullable=False)
    document_path: Mapped[str] = mapped_column(String(1000), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    modified_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )

    user: Mapped[Users] = relationship(back_populates="documents")
    reports: Mapped[list[Report]] = relationship(
        back_populates="document", cascade="all, delete-orphan"
    )


class Report(Base):
    __tablename__ = "reports"

    report_id: Mapped[uuid.UUID] = _pk()
    report_name: Mapped[str] = mapped_column(String(255), nullable=False)
    document_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("documents.document_id", ondelete="CASCADE"), nullable=False, index=True
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    classification: Mapped[str] = mapped_column(String(50), nullable=False, default="Internal")
    # pending | generating | complete | partial | failed
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    # Why a report is partial or failed — surfaced by GET /reports/{id}/status.
    error_detail: Mapped[str | None] = mapped_column(Text)

    user: Mapped[Users] = relationship(back_populates="reports")
    document: Mapped[Document] = relationship(back_populates="reports")
    attack_types: Mapped[list[AttackType]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    risk_assessments: Mapped[list[RiskAssessment]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    vulnerabilities: Mapped[list[Vulnerability]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    anomalies: Mapped[list[Anomaly]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    timeline: Mapped[list[Timeline]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )


class AttackType(Base):
    __tablename__ = "attack_types"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    attack_name: Mapped[str | None] = mapped_column(String(255))
    attack_mitre_technique_id: Mapped[str | None] = mapped_column(String(50))
    attack_mitre_technique_name: Mapped[str | None] = mapped_column(String(255))
    attack_description: Mapped[str | None] = mapped_column(Text)
    # The prototype flattens each attack's nested risk assessment into these
    # columns. Phase 1 aligns the generator's output with these names.
    risk_name: Mapped[str | None] = mapped_column(String(255))
    risk_description: Mapped[str | None] = mapped_column(Text)
    risk_level: Mapped[str | None] = mapped_column(String(50))
    impact: Mapped[str | None] = mapped_column(Text)
    likelihood: Mapped[str | None] = mapped_column(String(50))
    mitigation: Mapped[str | None] = mapped_column(Text)

    report: Mapped[Report] = relationship(back_populates="attack_types")


class RiskAssessment(Base):
    __tablename__ = "risk_assessments"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    risk_name: Mapped[str | None] = mapped_column(String(255))
    risk_description: Mapped[str | None] = mapped_column(Text)
    risk_level: Mapped[str | None] = mapped_column(String(50))
    impact: Mapped[str | None] = mapped_column(Text)
    likelihood: Mapped[str | None] = mapped_column(String(50))
    mitigation: Mapped[str | None] = mapped_column(Text)

    report: Mapped[Report] = relationship(back_populates="risk_assessments")


class Vulnerability(Base):
    __tablename__ = "vulnerabilities"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    vulnerability_name: Mapped[str | None] = mapped_column(String(255))
    vulnerability_description: Mapped[str | None] = mapped_column(Text)
    cve_id: Mapped[str | None] = mapped_column(String(50))
    cve_description: Mapped[str | None] = mapped_column(Text)
    cwe_id: Mapped[str | None] = mapped_column(String(50))
    cwe_description: Mapped[str | None] = mapped_column(Text)

    report: Mapped[Report] = relationship(back_populates="vulnerabilities")


class Anomaly(Base):
    __tablename__ = "anomalies"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    # `anomaly_id`, `user_id` and `user_name` below are values the LLM extracted
    # from the log itself — the analyst-facing identifiers. They are NOT row keys
    # and NOT foreign keys into `users`; a log can name a principal this system
    # has never heard of.
    anomaly_id: Mapped[str | None] = mapped_column(String(100))
    anomaly_name: Mapped[str | None] = mapped_column(String(255))
    user_id: Mapped[str | None] = mapped_column(String(255))
    user_name: Mapped[str | None] = mapped_column(String(255))
    source_ip: Mapped[str | None] = mapped_column(String(100))
    destination_ip: Mapped[str | None] = mapped_column(String(100))
    protocol: Mapped[str | None] = mapped_column(String(50))
    counted: Mapped[int | None] = mapped_column(Integer)
    first_occurrence: Mapped[str | None] = mapped_column(String(100))
    last_occurrence: Mapped[str | None] = mapped_column(String(100))

    report: Mapped[Report] = relationship(back_populates="anomalies")


class Timeline(Base):
    __tablename__ = "timeline_events"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    event_name: Mapped[str | None] = mapped_column(String(255))
    entity: Mapped[str | None] = mapped_column(String(255))
    time_stamp: Mapped[str | None] = mapped_column(String(100))
    duration: Mapped[str | None] = mapped_column(String(100))

    report: Mapped[Report] = relationship(back_populates="timeline")


class Chat(Base):
    __tablename__ = "chats"

    chat_id: Mapped[uuid.UUID] = _pk()
    chat_name: Mapped[str] = mapped_column(String(255), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    attached_documents: Mapped[list] = mapped_column(JSON, nullable=False, default=list)

    user: Mapped[Users] = relationship(back_populates="chats")
    messages: Mapped[list[Message]] = relationship(
        back_populates="chat", cascade="all, delete-orphan"
    )


class Message(Base):
    __tablename__ = "messages"

    message_id: Mapped[uuid.UUID] = _pk()
    chat_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("chats.chat_id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String(50), nullable=False)
    context: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="complete")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    chat: Mapped[Chat] = relationship(back_populates="messages")
