"""SQLAlchemy models.

Table *shapes* are carried over from the prototype (see PORTING.md) so the
ported report/RAG logic keeps working. Three deliberate changes:

1. **UUID primary keys** replace the prototype's parsed sequential strings
   ("UR-1001" -> "UR-1002"). Those were generated by reading the max existing
   id, string-slicing it and adding one, which sorted lexicographically
   ("REP-999" > "REP-1000") and raced between concurrent requests.
2. **Lowercase table names.** The prototype used "USER", which is a reserved
   word in Postgres and only worked because SQLAlchemy quoted it.
3. **`server_default=func.now()`** instead of `default=datetime.now()`. The
   latter evaluates once at import, so every row in a given process shares the
   process start time.

Column names within each table are otherwise unchanged.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    Uuid,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


def _pk() -> Mapped[uuid.UUID]:
    return mapped_column(Uuid, primary_key=True, default=uuid.uuid4)


class Users(Base):
    __tablename__ = "users"

    user_id: Mapped[uuid.UUID] = _pk()
    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True, index=True)
    role: Mapped[str] = mapped_column(String(50), nullable=False, default="analyst")
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="Active")
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    phone_number: Mapped[str | None] = mapped_column(String(50))
    # bcrypt hash. Never a plaintext password — see CLAUDE.md > Hard rules.
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    organization: Mapped[str] = mapped_column(String(255), nullable=False, default="-")
    location: Mapped[str] = mapped_column(String(255), nullable=False, default="UAE")
    bio: Mapped[str | None] = mapped_column(Text)
    photo_path: Mapped[str | None] = mapped_column(String(500))
    mfa: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    documents: Mapped[list[Document]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    reports: Mapped[list[Report]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    chats: Mapped[list[Chat]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    api_keys: Mapped[list[ApiKey]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class Document(Base):
    __tablename__ = "documents"

    document_id: Mapped[uuid.UUID] = _pk()
    document_name: Mapped[str] = mapped_column(String(255), nullable=False)
    document_size: Mapped[float] = mapped_column(Float, nullable=False)
    document_extension: Mapped[str] = mapped_column(String(20), nullable=False)
    document_path: Mapped[str] = mapped_column(String(1000), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    modified_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )

    user: Mapped[Users] = relationship(back_populates="documents")
    reports: Mapped[list[Report]] = relationship(
        back_populates="document", cascade="all, delete-orphan"
    )


class Report(Base):
    __tablename__ = "reports"

    report_id: Mapped[uuid.UUID] = _pk()
    report_name: Mapped[str] = mapped_column(String(255), nullable=False)
    document_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("documents.document_id", ondelete="CASCADE"), nullable=False, index=True
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    classification: Mapped[str] = mapped_column(String(50), nullable=False, default="Internal")
    # pending | generating | complete | partial | failed
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    # Why a report is partial or failed — surfaced by GET /reports/{id}/status.
    error_detail: Mapped[str | None] = mapped_column(Text)

    # --- File integrity (Phase 5) ---------------------------------------
    # The SHA-256 of the source document *as it was when this report was
    # generated*. It lives on the report, not the document: a report is a
    # statement about a file at a point in time, and re-hashing the document
    # row would only ever tell you what the file is now.
    file_hash: Mapped[str | None] = mapped_column(String(64))
    # UNKNOWN — never checked | SEALED — matches | TAMPERED — does not.
    integrity_state: Mapped[str] = mapped_column(
        String(20), nullable=False, default="UNKNOWN", server_default="UNKNOWN"
    )
    integrity_checked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    user: Mapped[Users] = relationship(back_populates="reports")
    document: Mapped[Document] = relationship(back_populates="reports")
    attack_types: Mapped[list[AttackType]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    risk_assessments: Mapped[list[RiskAssessment]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    vulnerabilities: Mapped[list[Vulnerability]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    anomalies: Mapped[list[Anomaly]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    timeline: Mapped[list[Timeline]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    threat_intel: Mapped[list[ThreatIntel]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    alerts: Mapped[list[SecurityAlert]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )
    shares: Mapped[list[ReportShare]] = relationship(
        back_populates="report", cascade="all, delete-orphan"
    )


class AttackType(Base):
    __tablename__ = "attack_types"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    attack_name: Mapped[str | None] = mapped_column(String(255))
    attack_mitre_technique_id: Mapped[str | None] = mapped_column(String(50))
    attack_mitre_technique_name: Mapped[str | None] = mapped_column(String(255))
    attack_description: Mapped[str | None] = mapped_column(Text)
    # The prototype flattens each attack's nested risk assessment into these
    # columns. Phase 1 aligns the generator's output with these names.
    risk_name: Mapped[str | None] = mapped_column(String(255))
    risk_description: Mapped[str | None] = mapped_column(Text)
    risk_level: Mapped[str | None] = mapped_column(String(50))
    impact: Mapped[str | None] = mapped_column(Text)
    likelihood: Mapped[str | None] = mapped_column(String(50))
    mitigation: Mapped[str | None] = mapped_column(Text)

    report: Mapped[Report] = relationship(back_populates="attack_types")


class RiskAssessment(Base):
    __tablename__ = "risk_assessments"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    risk_name: Mapped[str | None] = mapped_column(String(255))
    risk_description: Mapped[str | None] = mapped_column(Text)
    risk_level: Mapped[str | None] = mapped_column(String(50))
    impact: Mapped[str | None] = mapped_column(Text)
    likelihood: Mapped[str | None] = mapped_column(String(50))
    mitigation: Mapped[str | None] = mapped_column(Text)

    report: Mapped[Report] = relationship(back_populates="risk_assessments")


class Vulnerability(Base):
    __tablename__ = "vulnerabilities"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    vulnerability_name: Mapped[str | None] = mapped_column(String(255))
    vulnerability_description: Mapped[str | None] = mapped_column(Text)
    cve_id: Mapped[str | None] = mapped_column(String(50))
    cve_description: Mapped[str | None] = mapped_column(Text)
    cwe_id: Mapped[str | None] = mapped_column(String(50))
    cwe_description: Mapped[str | None] = mapped_column(Text)

    report: Mapped[Report] = relationship(back_populates="vulnerabilities")


class Anomaly(Base):
    __tablename__ = "anomalies"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    # `anomaly_id`, `user_id` and `user_name` below are values the LLM extracted
    # from the log itself — the analyst-facing identifiers. They are NOT row keys
    # and NOT foreign keys into `users`; a log can name a principal this system
    # has never heard of.
    anomaly_id: Mapped[str | None] = mapped_column(String(100))
    anomaly_name: Mapped[str | None] = mapped_column(String(255))
    user_id: Mapped[str | None] = mapped_column(String(255))
    user_name: Mapped[str | None] = mapped_column(String(255))
    source_ip: Mapped[str | None] = mapped_column(String(100))
    destination_ip: Mapped[str | None] = mapped_column(String(100))
    protocol: Mapped[str | None] = mapped_column(String(50))
    counted: Mapped[int | None] = mapped_column(Integer)
    first_occurrence: Mapped[str | None] = mapped_column(String(100))
    last_occurrence: Mapped[str | None] = mapped_column(String(100))

    report: Mapped[Report] = relationship(back_populates="anomalies")


class Timeline(Base):
    __tablename__ = "timeline_events"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    event_name: Mapped[str | None] = mapped_column(String(255))
    entity: Mapped[str | None] = mapped_column(String(255))
    time_stamp: Mapped[str | None] = mapped_column(String(100))
    duration: Mapped[str | None] = mapped_column(String(100))

    report: Mapped[Report] = relationship(back_populates="timeline")


class ThreatIntel(Base):
    """Enrichment for one indicator observed in a report's source log.

    Produced by the n8n orchestrator (AbuseIPDB reputation, its IOC
    classification pass) and persisted alongside the report so the Report
    Detail page can show where an indicator's score came from. The raw provider
    response is kept in `raw` — a score without its evidence is not something
    an analyst can act on.
    """

    __tablename__ = "threat_intel"

    id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    indicator: Mapped[str] = mapped_column(String(500), nullable=False)
    # ip | hash | domain — what kind of thing `indicator` is.
    indicator_type: Mapped[str] = mapped_column(String(50), nullable=False)
    # The workflow's own classification, e.g. "External Infrastructure".
    category: Mapped[str | None] = mapped_column(String(120))
    # abuseipdb | virustotal | n8n
    source: Mapped[str] = mapped_column(String(50), nullable=False, default="n8n")
    # AbuseIPDB's 0–100 confidence, or an equivalent from another provider.
    reputation_score: Mapped[int | None] = mapped_column(Integer)
    risk_level: Mapped[str | None] = mapped_column(String(50))
    country: Mapped[str | None] = mapped_column(String(10))
    usage_type: Mapped[str | None] = mapped_column(String(120))
    raw: Mapped[dict | None] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    report: Mapped[Report] = relationship(back_populates="threat_intel")


class SecurityAlert(Base):
    """Something a workflow or the app wants an analyst to look at.

    `user_id` is who the alert belongs to — the owner of the report it concerns
    — so alerts scope exactly like reports do. `source` is which workflow or
    subsystem raised it, because "who is telling me this" is the first question
    an analyst asks about an alert they did not expect.
    """

    __tablename__ = "security_alerts"

    alert_id: Mapped[uuid.UUID] = _pk()
    severity: Mapped[str] = mapped_column(String(50), nullable=False, default="medium")
    source: Mapped[str] = mapped_column(String(120), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    # open | resolved. The dashboard's "open alerts" count reads this.
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="open", server_default="open"
    )
    report_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), index=True
    )
    document_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("documents.document_id", ondelete="CASCADE"), index=True
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    report: Mapped[Report | None] = relationship(back_populates="alerts")


class ReportShare(Base):
    """A read-only share link for one report — see `core/share_token.py`.

    Only the SHA-256 of the token is stored, so a leaked database row cannot be
    replayed as a link. `prefix` is the clear, uniquely indexed lookup component.

    Revocation and expiry are both recorded here rather than implied, because
    both have to be enforced on the read path: a link that the UI has stopped
    listing is not a link that has stopped working.

    `classification_at_share` and `override_justification` are the audit trail
    for sharing a Confidential report. The justification is the override —
    `resolve_share` treats its presence as the recorded permission, so a report
    later raised to Confidential does not silently keep serving links that were
    issued when it was Internal.
    """

    __tablename__ = "report_shares"

    share_id: Mapped[uuid.UUID] = _pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.report_id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Who issued the link. Not exposed on the public view — see
    # `schemas/share.py` on why a share leaks no identity.
    created_by: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    prefix: Mapped[str] = mapped_column(String(32), nullable=False, unique=True, index=True)
    token_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    label: Mapped[str | None] = mapped_column(String(120))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # Null means the link does not expire. Revocation is then the only way to
    # retire it, which is why revocation exists rather than a shorter default.
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_viewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    view_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )
    classification_at_share: Mapped[str] = mapped_column(String(50), nullable=False)
    override_justification: Mapped[str | None] = mapped_column(Text)

    report: Mapped[Report] = relationship(back_populates="shares")


class ApiKey(Base):
    """A long-lived credential for a machine caller — see `core/api_key.py`.

    Only the SHA-256 of the secret is stored; `prefix` is the clear, uniquely
    indexed lookup component so verification never scans the table.
    """

    __tablename__ = "api_keys"

    key_id: Mapped[uuid.UUID] = _pk()
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    prefix: Mapped[str] = mapped_column(String(32), nullable=False, unique=True, index=True)
    key_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # Null means "does not expire" — which is the point for a scheduled
    # workflow. Revocation, not expiry, is how such a key is retired.
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )

    user: Mapped[Users] = relationship(back_populates="api_keys")


class Chat(Base):
    __tablename__ = "chats"

    chat_id: Mapped[uuid.UUID] = _pk()
    chat_name: Mapped[str] = mapped_column(String(255), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    attached_documents: Mapped[list] = mapped_column(JSON, nullable=False, default=list)

    user: Mapped[Users] = relationship(back_populates="chats")
    messages: Mapped[list[Message]] = relationship(
        back_populates="chat",
        cascade="all, delete-orphan",
        # Ordered here rather than at each call site: a transcript rendered in
        # insertion order is a correctness bug, not a display preference.
        order_by="Message.created_at",
    )


class Message(Base):
    __tablename__ = "messages"

    message_id: Mapped[uuid.UUID] = _pk()
    chat_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("chats.chat_id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String(50), nullable=False)
    context: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="complete")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    chat: Mapped[Chat] = relationship(back_populates="messages")


class AuthAttempt(Base):
    """One authentication attempt, kept only long enough to rate-limit on.

    This is rate-limit *state*, not the audit trail — `AuditLog` is that, and
    it is append-only and permanent. These rows are counted inside a sliding
    window and pruned; see `services/ratelimit.py`.

    `identifier` holds a source address or a lowercased email, never a password
    and never a token. There is no foreign key to `users`: an attempt against
    an address nobody has registered is exactly the attempt worth counting.

    `at` is stamped by the application rather than by `func.now()` on purpose.
    The window arithmetic uses the application clock, and mixing a database
    clock into one side of a comparison makes the window silently wider or
    narrower by however far the two containers have drifted.
    """

    __tablename__ = "auth_attempts"

    attempt_id: Mapped[uuid.UUID] = _pk()
    # ip | account
    scope: Mapped[str] = mapped_column(String(20), nullable=False)
    identifier: Mapped[str] = mapped_column(String(255), nullable=False)
    # login | register | password_change | share
    action: Mapped[str] = mapped_column(String(40), nullable=False)
    successful: Mapped[bool] = mapped_column(Boolean, nullable=False)
    at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        # Every read is "count rows for this (scope, identifier, action) newer
        # than T", so the index carries all four columns in that order.
        Index("ix_auth_attempts_window", "scope", "identifier", "action", "at"),
        # Pruning scans by age alone.
        Index("ix_auth_attempts_at", "at"),
    )


class AuditLog(Base):
    """Append-only record of security-relevant actions.

    Immutability is enforced twice, because one of the two is only a
    convention: the API exposes no update or delete path, *and* a Postgres
    trigger raises on UPDATE or DELETE against this table. The trigger is the
    one that survives somebody adding a well-meaning admin endpoint later.

    **There is deliberately no foreign key on `actor_id`.** Every other actor
    reference in this schema cascades on delete, which is right for data owned
    by a user and catastrophic here: deleting a user would erase the record of
    what that user did, which is the single most interesting case the log
    exists for. The uuid is stored unenforced and `actor_label` keeps the
    address as it read at the time, so a deleted actor stays legible.

    `correlation_id` is unused in Phase 8 and filled in by Phase 9's request
    middleware. The column exists now so the log does not need a migration to
    become traceable.

    What must never land here: passwords, JWTs, API key secrets, share tokens,
    or document contents. `services/audit.py` redacts by key name and caps
    value length rather than trusting call sites.
    """

    __tablename__ = "audit_log"

    audit_id: Mapped[uuid.UUID] = _pk()
    at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    # Dotted and closed — see `services/audit.py::ACTIONS`.
    action: Mapped[str] = mapped_column(String(60), nullable=False, index=True)
    # success | failure | blocked
    outcome: Mapped[str] = mapped_column(String(20), nullable=False)
    # user | api_key | anonymous | system
    actor_type: Mapped[str] = mapped_column(String(20), nullable=False)
    actor_id: Mapped[uuid.UUID | None] = mapped_column(Uuid, index=True)
    # The actor's email (or an attempted one) as it read at the time.
    actor_label: Mapped[str | None] = mapped_column(String(255))
    target_type: Mapped[str | None] = mapped_column(String(60))
    # A string, not a uuid: targets are heterogeneous and some are not rows.
    target_id: Mapped[str | None] = mapped_column(String(64))
    source_ip: Mapped[str | None] = mapped_column(String(64))
    correlation_id: Mapped[str | None] = mapped_column(String(64), index=True)
    detail: Mapped[dict | None] = mapped_column(JSON)

    __table_args__ = (
        # The admin view filters by actor and by action, newest first.
        Index("ix_audit_log_actor_at", "actor_id", "at"),
        Index("ix_audit_log_action_at", "action", "at"),
    )
