"""phase 5: integrity, alerts, threat intel, api keys

Revision ID: 1fcaee149697
Revises: 8c1d8d4ef272
Create Date: 2026-08-10 02:33:08.806118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcaee149697'
down_revision: Union[str, None] = '8c1d8d4ef272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_security_alerts_document_id'), 'security_alerts', ['document_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_report_id'), 'security_alerts', ['report_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_user_id'), 'security_alerts', ['user_id'], unique=False)
    op.create_table('threat_intel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('indicator', sa.String(length=500), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('usage_type', sa.String(length=120), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intel_report_id'), 'threat_intel', ['report_id'], unique=False)
    op.add_column('reports', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('reports', sa.Column('integrity_state', sa.String(length=20), server_default='UNKNOWN', nullable=False))
    op.add_column('reports', sa.Column('integrity_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'integrity_checked_at')
    op.drop_column('reports', 'integrity_state')
    op.drop_column('reports', 'file_hash')
    op.drop_index(op.f('ix_threat_intel_report_id'), table_name='threat_intel')
    op.drop_table('threat_intel')
    op.drop_index(op.f('ix_security_alerts_user_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_report_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_document_id'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
