"""add report status and error_detail

Revision ID: 8c1d8d4ef272
Revises: b193699810b3
Create Date: 2026-08-10 00:15:27.856047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1d8d4ef272'
down_revision: Union[str, None] = 'b193699810b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('error_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'error_detail')
    op.drop_column('reports', 'status')
    # ### end Alembic commands ###
